"use client";

import { useEffect, useState } from "react";
import type { PortfolioGrant } from "@/lib/types";

type BriefingResponse = {
  briefing: string;
  recommended_action: string;
  source: "cache" | "claude" | "fallback";
};

type State =
  | { kind: "loading" }
  | { kind: "ready"; data: BriefingResponse }
  | { kind: "error"; message: string };

export function BriefingCard({ grant, initial }: { grant: PortfolioGrant; initial: string }) {
  const [state, setState] = useState<State>({ kind: "loading" });

  useEffect(() => {
    const ctl = new AbortController();
    (async () => {
      try {
        const res = await fetch("/api/briefing", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ grant }),
          signal: ctl.signal,
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const json = (await res.json()) as BriefingResponse;
        setState({ kind: "ready", data: json });
      } catch (err) {
        if ((err as DOMException)?.name === "AbortError") return;
        setState({ kind: "error", message: String(err) });
      }
    })();
    return () => ctl.abort();
  }, [grant]);

  const provenance =
    state.kind === "ready"
      ? state.data.source === "claude"
        ? { label: "Generated by Claude · claude-sonnet-4-6", color: "#a78bfa" }
        : state.data.source === "cache"
          ? { label: "Cached briefing for demo entity", color: "#8b90a0" }
          : { label: "Deterministic synthesis (no LLM key configured)", color: "#8b90a0" }
      : null;

  return (
    <>
      <h2
        style={{
          fontSize: 12,
          textTransform: "uppercase",
          letterSpacing: 0.12,
          color: "var(--text-dim)",
          margin: "0 0 12px",
          display: "flex",
          alignItems: "center",
          gap: 10,
          flexWrap: "wrap",
        }}
      >
        <span>AI risk briefing</span>
        {provenance && (
          <span
            className="num"
            style={{
              fontSize: 11,
              fontWeight: 600,
              padding: "2px 8px",
              borderRadius: 3,
              border: `1px solid ${provenance.color}55`,
              background: `${provenance.color}18`,
              color: provenance.color,
              textTransform: "none",
              letterSpacing: 0.04,
            }}
          >
            {provenance.label}
          </span>
        )}
      </h2>
      <div
        style={{
          border: "1px solid #2a3142",
          background: "linear-gradient(180deg, #141821 0%, #11141a 100%)",
          borderRadius: 4,
          padding: "18px 20px",
          marginBottom: 16,
          fontSize: 14,
          lineHeight: 1.65,
          color: "var(--text)",
          minHeight: 80,
        }}
      >
        {state.kind === "loading" && (
          <p style={{ margin: 0, color: "var(--text-dim)", fontStyle: "italic" }}>
            Composing briefing from cross-source evidence…
          </p>
        )}
        {state.kind === "ready" && <p style={{ margin: 0 }}>{state.data.briefing}</p>}
        {state.kind === "error" && <p style={{ margin: 0 }}>{initial}</p>}
      </div>
      {state.kind === "ready" && (
        <>
          <div
            style={{
              borderLeft: "3px solid var(--amber, #d4a017)",
              padding: "10px 16px",
              marginBottom: 12,
              background: "rgba(232, 163, 23, 0.06)",
              fontSize: 13,
              lineHeight: 1.55,
              color: "var(--text)",
            }}
          >
            <span
              style={{
                display: "inline-block",
                fontSize: 11,
                fontWeight: 700,
                letterSpacing: 0.12,
                textTransform: "uppercase",
                color: "var(--amber, #d4a017)",
                marginRight: 8,
              }}
            >
              Recommended action
            </span>
            {state.data.recommended_action}
          </div>
          <div
            className="num"
            style={{
              marginBottom: 28,
              padding: "8px 14px",
              fontSize: 11,
              color: "var(--text-dim)",
              border: "1px solid var(--border)",
              borderRadius: 3,
              lineHeight: 1.7,
              background: "var(--bg-1)",
            }}
          >
            <span style={{ fontWeight: 700, letterSpacing: 0.08, marginRight: 6 }}>SOURCES</span>
            <a
              href={`https://api.fac.gov/findings?auditee_uei=eq.${grant.grant.recipient_uei}`}
              target="_blank"
              rel="noreferrer"
              style={{ color: "#c084fc", textDecoration: "underline", marginRight: 12 }}
            >
              api.fac.gov/findings
            </a>
            <a
              href={`https://api.usaspending.gov/api/v2/awards/${encodeURIComponent(
                grant.grant.award_id,
              )}/`}
              target="_blank"
              rel="noreferrer"
              style={{ color: "#60a5fa", textDecoration: "underline", marginRight: 12 }}
            >
              api.usaspending.gov
            </a>
            <a
              href={`https://api.sam.gov/entity-information/v4/entities?ueiSAM=${grant.grant.recipient_uei}`}
              target="_blank"
              rel="noreferrer"
              style={{ color: "#fb923c", textDecoration: "underline", marginRight: 12 }}
            >
              api.sam.gov
            </a>
            <span style={{ color: "var(--text-dim)" }}>
              · UEI {grant.grant.recipient_uei}
            </span>
          </div>
        </>
      )}
    </>
  );
}
